services:
  prism:
    build:
      context: ./PRISM
    image: prism:local
    container_name: prism
    network_mode: "service:simulator"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./PRISM:/opt/prism:ro
    tty: true
    restart: unless-stopped
    depends_on:
      - simulator
    command: ./build/prism eth0

  simulator:
    build:
      context: ./PRISM_simulator
    image: prism_simulator:local
    container_name: prism_simulator
    networks:
      sim_net: {}
    volumes:
      - ./PRISM_simulator:/opt/simulator:ro
    tty: true
    restart: unless-stopped
    environment:
      - ROLE=simulator
    command: /usr/local/bin/sim-api

  hmi:
    build:
      context: ./PRISM_simulator
      dockerfile: hmi/Dockerfile
    image: prism_hmi:local
    container_name: hmi
    networks:
      - sim_net
    tty: true
    restart: "no"
    ports:
      - "9000:8080"
    environment:
      - TARGET_HOST=simulator
    depends_on:
      - simulator
 

networks:
  sim_net:
    driver: bridge

